### ISSUE TITLE
Things that are not working in the bootcamp-hub

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#105]
ok @betatim here is where i've gotten today with the hub!

It works but ONLY with organization based authentication. Can you have a look at the hub and help me understand how to 

1. add a whitelist that actually works to the hub. what i have does not work.
2. add admins to the hub that can shutdown servers. i actually ended up killing pods at the command line a few times. it would be great to have admin access to this hub. 

then please see the other issues i posted with questions on managing a hub... so we can perhaps update docs accordingly. Thank you!!

**Comment by betatim** [comment]
I think #106 fixes both of your points. Closing this issue, feel free to reopen it though :)
