### ISSUE TITLE
Earth analytics course hub

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#117]
This issue is a check list of things that need to be done, information gathered and questions relevant to deploying a hub for Leah's semester long course.

* [x] class size **~28 - expect 23-30 - you never know who will drop**
* [ ] git repo containing the material to sync to students **i need to make something! but i know how to add it**
* [x] memory requirement - **similar to the spatial data workshop to begin with? then we can scale back**
* [x] login/authentication system **github whitelist but for the first day i'll collect github usernames so first day just github**
* [x] software libraries needed **earth analytics envt just like the workshop!**
* [x] install nbzip with zip support (just got merged) https://github.com/data-8/nbzip/archive/b32bd3441a760a518f0bcdd55def6ac247d471d8.zip  **yay is this to download zip vs tar files?**
* [x] the hub needs a name: ea-hub
  - rename the existing [earthhub chart](https://github.com/earthlab/hub-ops/tree/master/earthhub)
* [x] are student names known upfront? **no - please see above - my plan is to use generic github and then move to a whitelist**
* [ ] going live date -- **aug 29 - i'd prefer the 28th in the evening!**
* [x] use jupyterhub v0.9.2 with self-restarting hub

Please edit this message to add things to the list and answer questions by writing the answer after it.

Let's discuss things that need discussing in comments in this thread.

**Comment by betatim** [comment]
"it should pretty much be the same as the bootcamp hub i think" says Leah.

**Comment by lwasser** [comment]
yes! or the workshop hub :) i need the earth analytics environment running.

**Comment by betatim** [comment]
https://github.com/earthlab/hub-ops/tree/master/ea-hub contains the configuration for the hub.

It is already up and running: https://hub.earthdatascience.org/ea-hub/hub/home

**Comment by lwasser** [comment]
i think we can close this. What do you think @betatim ?
