### ISSUE TITLE
leah's breaking & fixing things again 

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#128]
Hey @betatim 
i'm running into some issues with my ea-hub setup.

for one i keep getting this error: 0 this happens when i use the conda tab in jupyter. i suppose we could remove it since terminal works quite well.

![screen shot 2018-09-04 at 8 21 37 pm](https://user-images.githubusercontent.com/7649194/45067379-2eaa1100-b080-11e8-82c8-b590f053f02b.png)

i'm not sure what is causing this. do you have any idea?
*****

I fixed the issue i had as a second issue but now have a new one

## ISSUE 3
`import earthpy` is throwing an error. on the hub tho not locally. i am tracing it back to `rasterio` and then `gdal`, i am not sure what the issue is.

1. takeaway - i think we need a test to ensure packages not only are there but load on travis
2. i am not sure why gdal is throwing errors which impacts rasterio and then earthpy. 

Here is the error:
![screen shot 2018-09-04 at 8 32 59 pm](https://user-images.githubusercontent.com/7649194/45067766-bfcdb780-b081-11e8-9021-e262fe32d3df.png)
i can't recreate it locally. but i reverted to an older dockerimage and i'm good for now. but still need to update things.

## ISSUE 3
nbgitpuller is giving me problems. all i can say is when i try to add a repo is just seems to spin and spin and spin even tho it builds quickly and passes. what am i doing wrong? i may just remove it for tomorrow!

**Comment by lwasser** [comment]
UPDATE: i was able to rollback to a previous docker image and the packages all work. so i'm good for tomorrow but i'd really like to understand what is happening so i can update things for future.

**Comment by betatim** [comment]
I would remove the notebook extension that adds the conda tab. We only have one environment inside the hub anyway, so having the tab to manage them seems weird. What do you think?

For the gdal issue and travis: I think this should be something we do in the earthpy repo/travis or also here?

I will poke around a bit to see if I can work out what the problem is. Could you link/mention here the revision of earthpy that contains the "broken" state?

**Comment by lwasser** [comment]
sure
well and oddly @betatim  the envt worked just fine on my computer. it failed in the hub. 
Here is the envt -- the most recent commit is the 
https://github.com/earthlab/earth-analytics-python-env

this commit
https://github.com/earthlab/earth-analytics-python-env/commit/67f90f402f98447039850de6da27f5d79dca8a30

is where i added hydrofunctions to the envt. nothing special. nothing spatial either! but after this addition the docker container threw an error in when i tried to load

1. earthpy
2. rasterio
3. gdal

i traced the error back to something with Gdal but i could not recreate the error on my computer. I want to test things but am not sure how at this point.

**Comment by lwasser** [comment]
ok this has been resolved! closing!
