### ISSUE TITLE
how do i reinstate a hub

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#129]
i'm going to try to work through this here... but i think we need good docs on both removing and reinstating a hub. This is just a note for myself right now as i work through the docs. 

https://earthlab-hub-ops.readthedocs.io/en/latest/day-to-day.html#removing-a-hub

**Comment by betatim** [comment]
Good point.

On a high level reinstating a hub is the same process as adding a new one, except you skip the steps that aren't needed (for example creating the helm chart). Having better docs is always better though.
