### ISSUE TITLE
Add percentage to upload files button

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#137]
Currently when a student uploads a file, you have to click on "uploading". If the file takes some time, that uploading icon stays the same and it's hard to see if progress is being made. can we add a progress bar to the uploading button?

**Comment by lwasser** [comment]
@betatim ok sure. this has been more problematic in the past week. I watched on student almost refresh their computer as it was just "appearing" to do nothing yet it was uploading. it just took a while. Even something simply like a button that changed colors could be nice.

some way to sync files efficiently would be really great. should i ping the jupyter folks on this via that issue?

**Comment by betatim** [comment]
Reading https://github.com/jupyter/notebook/pull/3373 makes me think that (new) notebook versions should have a progressbar already 🤷‍♂️?

**Comment by betatim** [comment]
Deployed and works :)

**Comment by betatim** [comment]
Deployed and works :)
