### ISSUE TITLE
location of installation instructions for jupyter extensions 

### ISSUE THREAD

**Issue by kcranston** [earthlab/hub-ops#161]
We have two options for where to put the installation instructions for the jupyter extensions (i.e. anything that looks like `RUN jupyter serverextension enable --py <extension> --sys-prefix`, which would we need for nbgrader, nbzip, nbgitpuller). We can put them in the [user-images Dockerfile](https://github.com/earthlab/hub-ops/tree/master/user-images) or we can put them in the [earth-analytics-python-env Dockerfile](https://github.com/earthlab/earth-analytics-python-env/blob/master/Dockerfile). If we put them in the earth-analytics image, then we can just pull from Dockerhub, and the hub doesn't need to build another image just to install the extensions.

**Comment by lwasser** [comment]
where did these extensions end up? it seemed to me they are in the user-image rather than the ea-envt now. @kcranston  this issue isn't linked to a pr but should it be linked to that PR that was merged this weekend?

**Comment by kcranston** [comment]
They were always in the user-image, so the current location is the status quo. This is how PR #163 and #172 are set up. Given this: 

> nbgitpuller and zip are ONLY needed for the hub so i don't want to add it to the ea-envt.

I think this is the right choice.

**Comment by lwasser** [comment]
ok great. so let's close this and things will stand as they are. #172 does add gitpuller back. closign this. thanks @kcranston !!
