### ISSUE TITLE
There are student pods available for students we've removed

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#173]
Looking at the control panel, i noticed some student pods for students who do not exist in our whitelist anymore. what is the process for cleaning our and removing a pod? Are those pods still available and should we delete them via admin or the cloud terminal?

in the example below anne - `windage` i believe is frm last year. @jlpalomino should be able to confirm. yoji i suppose still is in the program so we could keep him??

<img width="1156" alt="Screen Shot 2019-08-30 at 3 24 13 PM" src="https://user-images.githubusercontent.com/7649194/64052006-46549200-cb3a-11e9-9c7e-29afff1be792.png">

**Comment by jlpalomino** [comment]
@lwasser Here is the full list of student pods that can be removed: katysill, mgraber, mlevis1, rbenzeev, shwh2628, and windnage. I think we can remove yojihigh for now and if he decides to return, we can add him back if needed.

**Comment by lwasser** [comment]
ok! i've merged your PR... so i'll look at that list and see what happens if we just delete the pod in the admin space!! you might be able to do that as well? do you have access tot he admin space? i don't see those users in our whitelist.

**Comment by lwasser** [comment]
ok great. i did a cleanup this morning. let's close this for now but you can also help manage these students in the admin panel. the thing i'm not sure about is whether that means the pod even exists. i thought those didn't exist when i checked google cloud but... let see!! thank you.

**Comment by jlpalomino** [comment]
shwh2628 was still there in the admin panel, so I deleted it. I can help manage the admin panel moving forward.

**Comment by lwasser** [comment]
oops - great catch. thank you @jlpalomino that would be great if you can manage that!! thank you.
