### ISSUE TITLE
Please create a repo that you'd like to use for the ea-hub

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#175]
hey @jlpalomino 

https://github.com/earthlab/hub-ops/blob/master/hub-charts/ea-hub/values.yaml#L40

this line in my merged PR was the one i was waitin to update. can you please create a new repo that you'd like to use and submit a PR that simply updates the link to link to the new public repo? conversely you can send me the link, and i can make the update. but we need to do this tomorrow as what is happening now is the old repo will be added to students pods!! i'm not sure how it will go if we change the repo name - but i suggest changing it and creating a new folder - maybe ea-lessons or ea-homework-notebooks or whatever you want to call it.

**Comment by jlpalomino** [comment]
I'll submit a PR now, but just in case my PR is not right, the link to the repo is the same one that I put in my comment before: https://github.com/earthlab-education/earth-analytics-bootcamp-fall-2019
