### ISSUE TITLE
Permissions, permissions, permissions

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#2]
Leah create "TravisDeployer" role in https://console.cloud.google.com/iam-admin/roles?project=ea-jupyter with these permission:
```

    container.clusters.get
    container.clusters.getCredentials
    container.clusters.list
    container.daemonSets.get
    container.daemonSets.list
    container.deployments.create
    container.deployments.get
    container.deployments.list
    container.deployments.update
    container.pods.get
    container.pods.list
    container.pods.portForward
    container.services.get
```

Tim create a service account "travis-deployer" on https://console.cloud.google.com/iam-admin/serviceaccounts?project=ea-jupyter that uses the new role. Get private key and add it to the repo in the `secrets/` directory.

**Comment by lwasser** [comment]
hey @betatim do you have sufficient permissions (permissions permissions!!) now? Or shall we leave this open?

**Comment by betatim** [comment]
Gonna leave this open till I've merged the changes to make travis be able to do our bidding.
