### ISSUE TITLE
specifications for HDR summer students hub needs

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#213]
we should think about resources we want to allocate to the hub fr the summer

* Python 
* rstudio server?? -- dirks' build has this. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/990 (i emailed dirk to have a look at his docker container)
* storage (10GB is a default for our courses)
* memory??? 

Questions

- [ ] If we want to increase storage do we have to shut down the hub completely? and if we shut it down do students lose their files?
- [ ] same question for increasing memory allocations
- [ ] what is the cost for storage? i can't figure that out but Dirk has some suggestions about making costs lower in his email.

**Comment by kcranston** [comment]
What do you want the new hub called? `https://hub.earthdatascience.org/hdr` or something else?

**Comment by lwasser** [comment]
@kcranston i was thinking edsc (earth data science corps) THANK YOU!!

**Comment by kcranston** [comment]
What's the link for gitpuller for this one?

**Comment by kcranston** [comment]
Also, it's probably better for @lwasser to do the [OAuth setup](file:///Users/karen/Documents/earthlab/hub-ops-kcranston/docs/build/html/authentication.html#step-1-create-a-oauth-application), otherwise the students will get a message about me wanting access, which will be confusing.

**Comment by kcranston** [comment]
What still needs to be done:

- [ ] authentication not set up yet
- [ ] need updated nbgitpuller link
- [ ] whitelist of students

**Comment by lwasser** [comment]
ok this hub is live and ready to go. all we need to do it update the whitelist for students. @jlpalomino can i please put you in charge of making that update? @lherwehe could also implement if if you want !!! We can close this issue once this is done!

**Comment by jlpalomino** [comment]
@lwasser I created the spreadsheet for the students to fill in their GitHub usernames, so we can plan to include a link to this spreadsheet when we message the students today or tomorrow, etc.

**Comment by lwasser** [comment]
awesome. thank you so much @jlpalomino !!

**Comment by lwasser** [comment]
closing this given the EDSC hub was launched!
