### ISSUE TITLE
Where is the storage allocated for pods in the hub?

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#219]
i see [here](https://github.com/earthlab/hub-ops/blob/master/monitoring/values.yaml#L32) that the PV is setup with a 20GB size. i think our hub values are 10Gi but i can't seem to find where that is allocated in our hub charts.

**Comment by kcranston** [comment]
We aren't setting it explicitly, which means the value is coming from the JupyterHub helm chart. Their [user storage docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-storage.html#size-of-storage-provisioned) mention the 10GB default.

**Comment by lwasser** [comment]
ahhhh this makes sense!! it was confusing me. So if we added something to our user chart like this: it would modify each pod to have 2 gigs of storage rather than 10? that would be good to document as well. 

```
singleuser:
  storage:
    capacity: 2Gi
```

**Comment by lwasser** [comment]
ok i'm closing this. we have an issue open about updating the storage page in the docs #224  so this issue can be closed. i think i understand how storage works now.
