### ISSUE TITLE
Downlad directories Button Returns Internal Server Error

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#276]
Right now the download directories tool is throwing a. 500 error!  will need to solve this quickly as it's required to submit assignments!! 

NOTE: this tool WORKS on the edsc hub. the edsc hub does have an older envt. i just updated everything to python 3.8

**Comment by lwasser** [comment]
https://github.com/ryanlovett/jupyter-tree-download/issues/5 

@kcranston and @nkorinek i will be out tomorrow and maybe friday... but maybe you can help track this issue for me while i'm out. good news - they students don't need this tool by next week to submit their assignments!!

**Comment by lwasser** [comment]
i wonder if for the time being, we can install the older version that i know works? that could be worth a try - so forcing the image to install 0.1.0 ?? 

https://github.com/earthlab/hub-ops/blob/master/user-images/ea-hub/Dockerfile#L12

but what's odd is i don't see huge changes in this tool since i installed it on the edsc hub. what could be causing this?

**Comment by kcranston** [comment]
Ryan's debugging suggestion worked, so let's try adding zip to the image.

**Comment by lwasser** [comment]
@kcranston amazing. if you test it on staging hub and it works feel free to just merge while i'm out!! MUCH appreciated. i'm assuming zip would be a pip install or something in that image installed? i was worried about troubleshooting that one!!

**Comment by lwasser** [comment]
ok this has been FIXED!! closing it!!
