### ISSUE TITLE
every commit is failing on the hub now

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#294]
it seems to be something with staging hub and the docker image. @kcranston are you able to see why this is happening? 

<img width="912" alt="Screen Shot 2020-10-09 at 11 34 48 AM" src="https://user-images.githubusercontent.com/7649194/95614301-8071b200-0a23-11eb-94f0-3dc7bb19f187.png">

**Comment by kcranston** [comment]
I can't see the dockerhub build pages (I get a 404, likely because I don't have access?).

**Comment by lwasser** [comment]
ahhh let me try to give you access @kcranston what's odd is my last update just passed. but every one before failed.

**Comment by lwasser** [comment]
ok i did add you to docker but this is where it's errorring!
so it looks like it just can't find that directory which i think makes sense maybe?

<img width="849" alt="Screen Shot 2020-10-20 at 11 50 09 AM" src="https://user-images.githubusercontent.com/7649194/96624813-88a2da80-12ca-11eb-8e81-436fa259ead1.png">

**Comment by lwasser** [comment]
@kcranston so you are getting the same 404 i am getting but you do have permissions. it looks like it's trying to build staging hub but that hub was moved off of the branch... i'll go through the code but i dont fully understand why it's still trying to deploy the staging hub container in this build with the user image gone. there is nothing to build. do you have any ideas?

**Comment by lwasser** [comment]
i hav ea theory - i just turned off the web hook in dockerhub for that image. maybe it's as simple as that.

**Comment by lwasser** [comment]
Fixed by removing the docker autobuild that i had in place for staging hub on dockerhub
