### ISSUE TITLE
Setup domain name for the hub

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#3]
Get domain name setup

**Comment by lwasser** [comment]
Ok! we will think about a domain for the hub :)

**Comment by lwasser** [comment]
Question for you @betatim i'd like to use our earthdatascience url. Have you ever set up something like hub.earthdatascience.org ?

i just haven't done it before. i'm working with godaddy. i can ask them too.. but just thought i'd ask you first.

**Comment by lwasser** [comment]
ahhh super helpful @betatim  i actually know how to setup a records. Thanks! so i will need the server IP as well to set this up.

**Comment by lwasser** [comment]
I think people so far seem to like hub.earthdatascience.org
BUT we could also do earthdatascience.org/hub/ i wonder if that is easier? are there pros and cons here?

**Comment by betatim** [comment]
I'd say https://earthdatascience.org/hub/ is slightly more tricky because it involves configuring the webserver that serves https://earthdatascience.org/ to forward things to the hub.

So unless there are strong opinions for http://earthdatascience.org/hub/ I'd vote against it ;)

**Comment by lwasser** [comment]
Thank you @betatim . People seem to like hub.earthdatascience.org 

Here is my question about this.
I know i  have a need for this hub for 3 courses this year and then potentially a workshop. I don't see a huge difference in the setup for each course EXCEPT for 

1. homework assignments will be different 
2. each class has a different group of students
SO - the grading and authentication will be different for each class even if the backend infrastructure is pretty much the same.

For those cases, how would we setup each class using hub.earthdatascience.org ? Can you kindly help me understand how this will work?
Thank you

**Comment by lwasser** [comment]
sure @betatim i'll close it now. is the sub-hub (that sounds very funny!!) . please create another issue if one is needed in addition to the multi-hub issue to address what we need to!

**Comment by betatim** [comment]
Decided that multi-hub was a better name than sub-hub (even though that has a better ing to it).
