### ISSUE TITLE
Travis and Hub Deployment - Currently I can't  deploy hub updates

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#310]
Currently there are a few issues with the hub 

1. Because travis is not running builds or atleast not consistently the deployments are no longer working
2. i tried to deploy locally and it's hanging

So essentially i can't update any of our hubs which is problematic. 
i'm not sure what the solution is yet. i've messaged travis.ci twice and also posted on their [discourse forums here.](https://travis-ci.community/t/builds-fully-hanging/10613). but so far there's been no response.

they are moving to the .org --> .com by the end of december . i attempted to migrate over  because our builds were taking so long and that was recommended but something is not working still. it says that we are out of credits but I think that has something to do with builds running for like 3 hours due to the migration. 

on some levels i consider whether we should move the hub to the education organization which should have many more credits ... here we are competing with other earth lab repos. But i hate having so many organizations that we are managing and want to think about cases when i'm not around and people are looking  for things.

i'm really open to ideas here @kcranston  @mbjoseph (max this relates to my email which i will respond to you about after i teach). this build is not a simple one to setup is the issue.

**Comment by kcranston** [comment]
Couple of thoughts:

* can we move all or parts of the build + deploy to GitHub Actions or CircleCI instead of travis? I just checked the Berkeley datahub, and it looks like they are using CircleCI (there is one Action, but it is minor check on branch merging rules)
* I think we should write a local_deploy.py script that does a local build + deploy. I know you are having problems with the local build, too, but I still think this would be a good thing to have with the length of time it takes to run everything. 
* I can't even find info about the failing builds. The last run I see in the build history is from 9 days ago.

**Comment by lwasser** [comment]
yes - @kcranston our builds have just halted. what happened is moving to .com they implement this new pricing scheme ... and builds got SUPER SLOW - like taking hours a month ago so i started the migration per their suggestions and then the credits hit. I suspect however the credits are in part due to how long the builds were taking. regardless i'm open to moving to actions ... right now i just need any way to update the hub. it's not working!

**Comment by lwasser** [comment]
just a note that here is my current convo with travis support. i think regardless if travis is moving to a paid model, perhaps we consider some of our tools running on actions for the time being. 
```

MK (Travis CI) Nov 19, 2020, 12:05 EST Hello Leah,Thanks for writing in and for confirming the requested details.We are awaiting further directives/approval from management on this and we will let you know once this is done.Thanks for your patience and we will be in touch.--MKYour Friends @Travis CITest and Deploy with Confidence.www.travis-ci.com—Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany \| GF/CEO: Randy Jacops \| Contact: contact@travis-ci.org \| Amtsgericht Charlottenburg, Berlin, HRB 140133 B \| Umsatzsteuer-ID gemäß §27 a Umsatzsteuergesetz: DE282002648 | MK (Travis CI) Nov 19, 2020, 12:05 EST Hello Leah,Thanks for writing in and for confirming the requested details.We are awaiting further directives/approval from management on this and we will let you know once this is done.Thanks for your patience and we will be in touch.--MKYour Friends @Travis CITest and Deploy with Confidence.www.travis-ci.com—Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany \| GF/CEO: Randy Jacops \| Contact: contact@travis-ci.org \| Amtsgericht Charlottenburg, Berlin, HRB 140133 B \| Umsatzsteuer-ID gemäß §27 a Umsatzsteuergesetz: DE282002648
-- | --
MK (Travis CI) Nov 19, 2020, 12:05 EST Hello Leah,Thanks for writing in and for confirming the requested details.We are awaiting further directives/approval from management on this and we will let you know once this is done.Thanks for your patience and we will be in touch.--MKYour Friends @Travis CITest and Deploy with Confidence.www.travis-ci.com—Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany \| GF/CEO: Randy Jacops \| Contact: contact@travis-ci.org \| Amtsgericht Charlottenburg, Berlin, HRB 140133 B \| Umsatzsteuer-ID gemäß §27 a Umsatzsteuergesetz: DE282002648


```

**Comment by lwasser** [comment]
@kcranston travis did add credits to our account but i'm worried that we are sharing credits with all of earth lab and could run out again and dont currently see travis running. may i ask - has any progress been made on deployment using another tool? i am totally happy with actions or CircleCi both are great. i'm also open to moving this to another organization if we have to but that is last resort. the problem is i have to update a few hubs now if possible and so it would be good to sort this out in the next few weeks. thank you!

**Comment by lwasser** [comment]
closing t his -  i t hink this is  resolved
