### ISSUE TITLE
Update location of grafana and prometheus charts

### ISSUE THREAD

**Issue by kcranston** [earthlab/hub-ops#311]
The grafana and prometheus helm charts defined in [monitoring/requirements.yaml](https://github.com/earthlab/hub-ops/blob/master/monitoring/requirements.yaml) are now deprecated, as per https://helm.sh/blog/new-location-stable-incubator-charts/ 

Following the link in that post to the new location - https://charts.helm.sh/stable - indicates that centralized hosting of helm charts is also being deprecated. The new charts for grafana and prometheus are now at:

* https://github.com/grafana/helm-charts
* https://github.com/prometheus-community/helm-charts

**Comment by lwasser** [comment]
oh gosh. so what does this mean for us @kcranston ??

**Comment by kcranston** [comment]
I think this is just a matter of updating the locations in the requirements.yaml file and re-deploying the hub. I'll make this change when I do the helm3 update (because I think both charts now require helm3).

**Comment by kcranston** [comment]
We don't currently have grafana and prometheus deployed on the new cluster. We've been fine so far using the monitoring tools in the GCloud interface, so I have not prioritized getting these back up and running. If the current situation is ok, I think we can close this.

**Comment by lwasser** [comment]
i think it's ok for now @kcranston . i will close it. in all of the years of the hub i haven't used those interfaces.
