### ISSUE TITLE
issues launching the hub

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#329]
hey @kcranston are you working on the hub? i can't seem to get in

<img width="1290" alt="Screen Shot 2021-01-21 at 12 52 15 PM" src="https://user-images.githubusercontent.com/7649194/105404729-890f8200-5be7-11eb-9e5f-3ca9c48e5e3c.png">

i will try again but i got the error above.

**Comment by kcranston** [comment]
Still having issues? I just logged in successfully? Don't see anything in the logs for your pod...

**Comment by lwasser** [comment]
i tried again and it worked. i'll keep this issue open to see if it happens again. i'll also see if any of the students run into issues! thank you, Karen.

**Comment by lwasser** [comment]
alsofixed. closing
