### ISSUE TITLE
resource scaling issues?

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#52]
ok @betatim i've been working on this a bit more and  i'm noticing some consistent errors. it seems like for whatever reason, a certain number of users are able to access the hub. and then ... it crashes because of insufficient resources. by crash i mean you can't login. see below. this is a new "error" where it's trying to launch but not explicitely telling me what the issue is until i click on the log. if i knew a bit more i may try to play around with the setup but i really don't want to break things! 
hoping this is a small thing to fix and that you see it in the morning pre-workshop which starts at 9am (5 your time). i will try to be up early just in case i can catch you!! 

i should have tested it with more people earlier in the day. i just saw that it worked and got excited and didn't think to test more. 
<img width="1115" alt="screen shot 2018-07-19 at 10 25 45 pm" src="https://user-images.githubusercontent.com/7649194/42983223-c573bfd0-8ba2-11e8-92e4-3981e14f275a.png">

**Comment by betatim** [comment]
Should have mentioned this more explicitly: the resources the whole cluster is allowed to use are fairly low right now as I wasn't expecting anyone wanting to use it seriously till later today (and run away resource usage is expensive). I thought I could switch to more and bigger nodes during the day today and hadn't thought that you might want to test things with several people.
