### ISSUE TITLE
Multi hub setup

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#7]
There will be several courses and workshops. Each with potentially their own set of students, required libraries/software, homework, and so on.

Instead of having one big JupyterHub instance that works for everyone, we will have one hub for each course.

Each hub will be reachable at http://hub.earthdatascience.org/earth-analytics or http://hub.earthdatascience.org/earth-workshop or http://hub.earthdatascience.org/something-something.

Technically we will make that happen by having an Ingress that takes care of directing traffic to each hub. Each hub will be configured by its own chart and deployed into a new namespace but on the same cluster (to share resources). The chart for each hub will reside in this repository as a distinct sub-directory. This should work well if we have "a few" hubs (like less than ten).

Each hub that uses the CU Google auth would need its own OAuth secrets and callback.

**Comment by lwasser** [comment]
thanks @betatim  this sounds good. i can't imagine having more than 10 anytime soon. i can see having up to 4 classes and then one other for workshops in the next 1-2 years.
