### ISSUE TITLE
Collect all hub charts in a directory

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#71]
Create a `hub-config` directory that contains all the charts for the various hubs.

Make sure to update the documentation, deploy script, etc

**Comment by lwasser** [comment]
i have a stupid question @betatim  related to this - all data management stuff. 
why is `Chart.yml` always capitalized but the others are lower case? Does that matter?

**Comment by betatim** [comment]
The structure of the directories that configure each hub come from how [helm charts](https://docs.helm.sh/developing_charts/#charts) are organised. I've never wondered why it is `Chart.yml` and not `chart.yml` :) To my shame I've also never experimented with lower vs uppercase. It might well work because I think OSX or Windows filesystems can't actually tell the difference(??).

**Comment by lwasser** [comment]
ok! this is something to explore. but i would like the hub-config dir so we can manage all of these hubs in one place! it's confusing now to have them all floating around :) so would love to sort this feature out! @betatim
