### ISSUE TITLE
Expected class sizes

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#84]
How many classes and of what size will be running next semester? Need some data so we can seutp things appropriately and do some simulations.

This is related to the cluster discussion in https://github.com/earthlab/hub-ops/issues/75#issuecomment-409272668

tagging @lwasser

**Comment by betatim** [comment]
For Monday we expect about 25 students plus 2-3 instructors so ~30 total.

1GB RAM and smaller than or workshop like limits of CPU.

This is for the bootcamp hub @lwasser right?

**Comment by lwasser** [comment]
Sorry @betatim yes... the good news is that students came to class READY... so i suspect we may only have a few using the hub today.

**Comment by betatim** [comment]
Closed in favour of more specific issues.
