### ISSUE TITLE
Command Line setup in the hub

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#86]
Ok @betatim  two new questions.

1. Can we setup the hub with git available? or is it available and ready to configure? i'll do some testing today.
2. What if we want to have multiple sets of files available for students from different hubs? <i'll do some testing on this today as well. >

**Comment by betatim** [comment]
`git` should just exist.

What do you mean with "multiple sets of files available for students from different hubs"? Pull in files from several GitHub repositories via nbgitpuller?

**Comment by lwasser** [comment]
git does work!
the second question has to do with using several nbgitpuller commands to pull files fr0m different repos. <we discussed this - this morning in slack> so i'd imagine
day-1
day-2
day-3 etc... so this is what i may try today after the class ends as a pr!! i'll ask @jlpalomino  about her ideal data structure.
`notebooks/day-1`  <- @betatim can we actually use nested data directories with the nbgitpuller call? 
or just have 
`day-1`
`day-2`
`day-3`

**Comment by betatim** [comment]
I think nested like `notebooks/day-1`, `notebooks/day-2`, etc should work. Might need us to also add a `mkdir -p notebooks` on the line before the first `nbgitpuller` command.

**Comment by lwasser** [comment]
ok i understand this workflow now too!! so i will close this issue.
