### ISSUE TITLE
Fetching data

### ISSUE THREAD

**Issue by betatim** [earthlab/hub-ops#9]
We need a nice way to pull data into a users home directory in a hub.

Files to bring in are listed here: https://github.com/earthlab/earthpy/blob/1c8df03f1e1b4c16e669b1a862f41cd1be047e3f/earthpy/io.py#L12

Some options:
* install the earthpy module in each hub's environment, then use earthy functionality to fetch data
* make a small script that uses the pod lifecycle hook to fetch the data at pod startup
* bake data into the docker image
* create a readmany PVC to store data and mount it

**Comment by lwasser** [comment]
Here is a bunch of issues that came up today. i'll reorganize this into more clear set of issues. 

- [ ] students will need a working space (can it be persistent?)
- for workshops it would need to be persistent for a few hours --> a few days
- for classes it would be persistent up to a semester or longer?

* the data would optimally need to be a mounted drive 

* can students download everything at the end to capture all of the work they did throughout the semester? 

* how would a student transfer a dataset that they downloaded from the internet into their home drive to do their home work???

drop box client?

**Comment by lwasser** [comment]
closing this too as we have addressed it!!
